[project]
name = "cloudless-mosaic"
version = "1.0.0"

[build]
engine = "cluster"


[build.cluster]
namespace = "eoap-dask-gateway"
serviceAccount = "kaniko-sa"
registry = "ghcr.io/eoap"
secret = "kaniko-secret"

[tools.cloudless-mosaic]
context = "cloudless-mosaic"
path = "cwl-workflows/monthly-composite.cwl#cloudless-mosaic"

[tools.eopf-sentinel-2]
context = "eopf-sentinel-2"
path = "cwl-workflows/eopf-sentinel-2.cwl#eopf-sentinel-2"

[[workflows]]
path = "cwl-workflows/monthly-composite.cwl#main"

[[workflows.tests]]
name = "cloudless-mosaic-test-1"
description = "Test case 1 for cloudless-mosaic."

[workflows.tests.params]
resolution = 100 
start-date = "2018-01-01"
end-date = "2020-12-31"
aoi = "-122.27508544921875,47.54687159892238,-121.96128845214844,47.745787772920934"
collection = "sentinel-2-l2a"
bands = ["nir", "red", "green"]
max_cloud_cover = 25
max_items = 1000 

[workflows.tests.execution.cluster]
usage_report = "usage.json"
tool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
dask_gateway = true
debug = true

[workflows.tests.execution.paths]
volume = "/calrissian/cloudless-mosaic"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"

[[workflows]]
path = "cwl-workflows/eopf-sentinel-2.cwl#main"

[[workflows.tests]]
name = "eopf-sentinel-2-test-1"
description = "Test case 1 for eopf-sentinel-2."

[workflows.tests.params]
resolution = 100 
item-url = "https://objectstore.eodc.eu:2222/e05ab01a9d56408d82ac32d69a5aae2a:sample-data/tutorial_data/cpm_v253/S2B_MSIL1C_20250113T103309_N0511_R108_T32TLQ_20250113T122458.zarr"

[workflows.tests.execution.cluster]
usage_report = "usage.json"
tool_logs_basepath = "logs"
max_ram = "4G"
max_cores = 8
pod_serviceaccount = "calrissian-sa"
dask_gateway = true
debug = true

[workflows.tests.execution.paths]
volume = "/calrissian/eopf-sentinel-2"
stdout = "results.json"
stderr = "app.log"
tmp_outdir_prefix = "tmp"
outdir = "results"