version: '3'

includes:
  remote: https://raw.githubusercontent.com/eoap/task-files/refs/heads/feature-2/build-test/Taskfile.yaml
  
tasks:
  build:
  - task: remote:build

  prepare:
  - task: remote:prepare

  test:
  - task: remote:test

  cloudless:
  - task: remote:test-by-index
    vars:
      VAR: 0